### ISSUE TITLE
LightLdapd fork future name and license.

### ISSUE THREAD

**Issue by dbaarda** [urbanserj/entente#5]
G'day again,

My fork has diverged fairly significantly from your 0.1.x branch with hardly any lines left that I've not touched in some way or another. I see your new master branch is radically different the 0.1.x branch I forked from. With entente you appear to be focusing on only providing fast auth support. With LightLdapd I'm starting to implement full rfc2307 support for both auth and nss_ldap. Given the divergence, I want to do two things with my fork that I want to check are OK with you;

1) Change the name everywhere from entente to lightldapd. Currently my fork still builds an entente binary with the same cmdline args as yours, but I want to change that. I will maintain you and entente in the credits as the inspiration and origin of lightldapd, but now it will be more clearly a different project.

2) I'm considering changing the license from MIT to GPL v3.0. Maybe I am overly optimistic, but I'm hopeful that when rfc2307 nss_ldap support is fully implemented, this will start to get wider use. If that happens, I'd like to encourage that any refinements or improvements are contributed back.

I hope this is OK by you. If you have objections or suggestions I'd be happy to discuss and resolve them.

**Comment by urbanserj** [comment]
Hi Donovan,

You can do anything with your project without any reference to this repo or my name. Our projects don't have common parts at the moment. I don't think I have any rights on your branch after you rewrote the code.

Thank you for your contributions! You made huge improvements for entente 0.1.x.

Have fun!
